language: ruby

rvm:
  - "2.4.1"

gemfile:
  - gemfiles/rails5.0.gemfile

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 'COVERAGE=true rake spec:travis'

bundler_args: --without headless debug

before_install:
  - gem install bundler
